---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: cargo
    directories:
      - "/"
      - "/artichoke-*"
      - "/mezzaluna-*"
      - "/scolapasta-*"
      - "/spinoso-*"
      - "/fuzz"
      - "/spec-runner"
      - "/ui-tests"
    schedule:
      interval: monthly
    groups:
      cargo-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
    groups:
      bundler-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      npm-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: cargo
    directory: "/fuzz"
    schedule:
      interval: monthly
    groups:
      cargo-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: cargo
    directory: "/spec-runner"
    schedule:
      interval: monthly
    groups:
      cargo-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
  - package-ecosystem: cargo
    directory: "/ui-tests"
    schedule:
      interval: monthly
    groups:
      cargo-deps:
        patterns:
          - "*"
    assignees:
      - lopopolo
    labels:
      - A-deps
