[package]
name = "spinoso-regexp"
version = "0.4.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
description = """
Regex implementation for Ruby Regexp core type in Artichoke Ruby
"""
keywords = ["artichoke", "onig", "regex", "regexp", "ruby"]
categories = ["data-structures", "parser-implementations"]
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
bitflags = "1.3.0"
bstr = { version = "1.4.0", default-features = false, features = ["alloc"] }
onig = { version = "6.4.0", optional = true, default-features = false }
posix-space = "1.0.2"
regex = { version = "1.7.0", default-features = false, features = ["std", "unicode-perl"] }
scolapasta-aref = { version = "0.1.0", path = "../scolapasta-aref" }
scolapasta-string-escape = { version = "0.3.0", path = "../scolapasta-string-escape", default-features = false }

[features]
default = ["oniguruma", "regex-full"]
oniguruma = ["dep:onig"]
regex-full = ["regex-perf", "regex-unicode"]
regex-perf = ["regex/perf"]
regex-unicode = ["regex/unicode"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
