[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
allow = []
deny = [
  { name = "time", version = ">=0.2.0" },
]
skip = [
  { name = "cfg-if", version = "0.1" },
]
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
