[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "MIT",
  "MIT-0",
  "Unicode-3.0",
]

[bans]
# bitflags transition to v2 and usually there are duplicates of `windows-sys` in
# the lockfile.
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
allow = []
deny = [
  { name = "time", version = ">=0.2.0" },
  # See https://github.com/artichoke/artichoke/pull/2564 for more context.
  { name = "dirs-sys", version = ">= 0.4.1" },
]
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
