# Artichoke crates always use the 2018 edition.
edition = "2018"

hard_tabs = false
newline_style = "Unix"

# Wider width lines and less-aggressive line breaking.
max_width = 119
use_small_heuristics = "Default"

use_field_init_shorthand = true
use_try_shorthand = true

group_imports = 'StdExternalCrate'
