[package]
name = "spinoso-array"
version = "0.7.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
description = """
Growable vector backends for the Ruby Array core type in Artichoke Ruby
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["array", "no_std", "spinoso", "vec", "vector"]
categories = ["data-structures", "no-std"]

[dependencies]
raw-parts = "1.0"
# 1.4.1 fixed UB when allocating zero-bytes for ZST element types.
# https://github.com/servo/rust-smallvec/releases/tag/v1.4.1
# 1.6.1 fixed a buffer overflow when calling `SmallVec::insert_many`.
# https://github.com/servo/rust-smallvec/issues/252
smallvec = { version = "1, >= 1.6.1", optional = true }
tinyvec = { version = "1.5", optional = true, default-features = false, features = ["alloc"] }

[features]
default = ["small-array", "tiny-array"]
# Add a `SmallArray` backend that implements the small vector optimization with
# the `smallvec` crate.
small-array = ["smallvec"]
# Add a `TinyArray` backend that implements the small vector optimization with
# the `tinyvec` crate.
tiny-array = ["tinyvec"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
