use crate::interpreter::Mrb;
use crate::load::MrbLoadSources;
use crate::MrbError;

pub fn init(interp: &Mrb) -> Result<(), MrbError> {
    interp.def_rb_source_file("mspec.rb", include_str!("mspec.rb"))?;
    interp.def_rb_source_file(
        "mspec/commands/mkspec.rb",
        include_str!("mspec/commands/mkspec.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/commands/mspec-ci.rb",
        include_str!("mspec/commands/mspec-ci.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/commands/mspec-run.rb",
        include_str!("mspec/commands/mspec-run.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/commands/mspec-tag.rb",
        include_str!("mspec/commands/mspec-tag.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/commands/mspec.rb",
        include_str!("mspec/commands/mspec.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/expectations.rb",
        include_str!("mspec/expectations.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/expectations/expectations.rb",
        include_str!("mspec/expectations/expectations.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/expectations/should.rb",
        include_str!("mspec/expectations/should.rb"),
    )?;
    interp.def_rb_source_file("mspec/guards.rb", include_str!("mspec/guards.rb"))?;
    interp.def_rb_source_file(
        "mspec/guards/block_device.rb",
        include_str!("mspec/guards/block_device.rb"),
    )?;
    interp.def_rb_source_file("mspec/guards/bug.rb", include_str!("mspec/guards/bug.rb"))?;
    interp.def_rb_source_file(
        "mspec/guards/conflict.rb",
        include_str!("mspec/guards/conflict.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/guards/endian.rb",
        include_str!("mspec/guards/endian.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/guards/feature.rb",
        include_str!("mspec/guards/feature.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/guards/guard.rb",
        include_str!("mspec/guards/guard.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/guards/platform.rb",
        include_str!("mspec/guards/platform.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/guards/quarantine.rb",
        include_str!("mspec/guards/quarantine.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/guards/superuser.rb",
        include_str!("mspec/guards/superuser.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/guards/support.rb",
        include_str!("mspec/guards/support.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/guards/version.rb",
        include_str!("mspec/guards/version.rb"),
    )?;
    interp.def_rb_source_file("mspec/helpers.rb", include_str!("mspec/helpers.rb"))?;
    interp.def_rb_source_file(
        "mspec/helpers/argf.rb",
        include_str!("mspec/helpers/argf.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/helpers/argv.rb",
        include_str!("mspec/helpers/argv.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/helpers/datetime.rb",
        include_str!("mspec/helpers/datetime.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/helpers/fixture.rb",
        include_str!("mspec/helpers/fixture.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/helpers/flunk.rb",
        include_str!("mspec/helpers/flunk.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/helpers/frozen_error_class.rb",
        include_str!("mspec/helpers/frozen_error_class.rb"),
    )?;
    interp.def_rb_source_file("mspec/helpers/fs.rb", include_str!("mspec/helpers/fs.rb"))?;
    interp.def_rb_source_file("mspec/helpers/io.rb", include_str!("mspec/helpers/io.rb"))?;
    interp.def_rb_source_file(
        "mspec/helpers/mock_to_path.rb",
        include_str!("mspec/helpers/mock_to_path.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/helpers/numeric.rb",
        include_str!("mspec/helpers/numeric.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/helpers/ruby_exe.rb",
        include_str!("mspec/helpers/ruby_exe.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/helpers/scratch.rb",
        include_str!("mspec/helpers/scratch.rb"),
    )?;
    interp.def_rb_source_file("mspec/helpers/tmp.rb", include_str!("mspec/helpers/tmp.rb"))?;
    interp.def_rb_source_file(
        "mspec/helpers/warning.rb",
        include_str!("mspec/helpers/warning.rb"),
    )?;
    interp.def_rb_source_file("mspec/matchers.rb", include_str!("mspec/matchers.rb"))?;
    interp.def_rb_source_file(
        "mspec/matchers/base.rb",
        include_str!("mspec/matchers/base.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_an_instance_of.rb",
        include_str!("mspec/matchers/be_an_instance_of.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_ancestor_of.rb",
        include_str!("mspec/matchers/be_ancestor_of.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_close.rb",
        include_str!("mspec/matchers/be_close.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_computed_by.rb",
        include_str!("mspec/matchers/be_computed_by.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_empty.rb",
        include_str!("mspec/matchers/be_empty.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_false.rb",
        include_str!("mspec/matchers/be_false.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_kind_of.rb",
        include_str!("mspec/matchers/be_kind_of.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_nan.rb",
        include_str!("mspec/matchers/be_nan.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_nil.rb",
        include_str!("mspec/matchers/be_nil.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_true.rb",
        include_str!("mspec/matchers/be_true.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/be_true_or_false.rb",
        include_str!("mspec/matchers/be_true_or_false.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/block_caller.rb",
        include_str!("mspec/matchers/block_caller.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/complain.rb",
        include_str!("mspec/matchers/complain.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/eql.rb",
        include_str!("mspec/matchers/eql.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/equal.rb",
        include_str!("mspec/matchers/equal.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/equal_element.rb",
        include_str!("mspec/matchers/equal_element.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_class_variable.rb",
        include_str!("mspec/matchers/have_class_variable.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_constant.rb",
        include_str!("mspec/matchers/have_constant.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_instance_method.rb",
        include_str!("mspec/matchers/have_instance_method.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_instance_variable.rb",
        include_str!("mspec/matchers/have_instance_variable.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_method.rb",
        include_str!("mspec/matchers/have_method.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_private_instance_method.rb",
        include_str!("mspec/matchers/have_private_instance_method.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_private_method.rb",
        include_str!("mspec/matchers/have_private_method.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_protected_instance_method.rb",
        include_str!("mspec/matchers/have_protected_instance_method.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_public_instance_method.rb",
        include_str!("mspec/matchers/have_public_instance_method.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/have_singleton_method.rb",
        include_str!("mspec/matchers/have_singleton_method.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/include.rb",
        include_str!("mspec/matchers/include.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/include_any_of.rb",
        include_str!("mspec/matchers/include_any_of.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/infinity.rb",
        include_str!("mspec/matchers/infinity.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/match_yaml.rb",
        include_str!("mspec/matchers/match_yaml.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/method.rb",
        include_str!("mspec/matchers/method.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/output.rb",
        include_str!("mspec/matchers/output.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/output_to_fd.rb",
        include_str!("mspec/matchers/output_to_fd.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/raise_error.rb",
        include_str!("mspec/matchers/raise_error.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/respond_to.rb",
        include_str!("mspec/matchers/respond_to.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/signed_zero.rb",
        include_str!("mspec/matchers/signed_zero.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/matchers/variable.rb",
        include_str!("mspec/matchers/variable.rb"),
    )?;
    interp.def_rb_source_file("mspec/mocks.rb", include_str!("mspec/mocks.rb"))?;
    interp.def_rb_source_file("mspec/mocks/mock.rb", include_str!("mspec/mocks/mock.rb"))?;
    interp.def_rb_source_file(
        "mspec/mocks/object.rb",
        include_str!("mspec/mocks/object.rb"),
    )?;
    interp.def_rb_source_file("mspec/mocks/proxy.rb", include_str!("mspec/mocks/proxy.rb"))?;
    interp.def_rb_source_file("mspec/runner.rb", include_str!("mspec/runner.rb"))?;
    interp.def_rb_source_file(
        "mspec/runner/actions.rb",
        include_str!("mspec/runner/actions.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/actions/filter.rb",
        include_str!("mspec/runner/actions/filter.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/actions/leakchecker.rb",
        include_str!("mspec/runner/actions/leakchecker.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/actions/tag.rb",
        include_str!("mspec/runner/actions/tag.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/actions/taglist.rb",
        include_str!("mspec/runner/actions/taglist.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/actions/tagpurge.rb",
        include_str!("mspec/runner/actions/tagpurge.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/actions/tally.rb",
        include_str!("mspec/runner/actions/tally.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/actions/timer.rb",
        include_str!("mspec/runner/actions/timer.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/context.rb",
        include_str!("mspec/runner/context.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/evaluate.rb",
        include_str!("mspec/runner/evaluate.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/example.rb",
        include_str!("mspec/runner/example.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/exception.rb",
        include_str!("mspec/runner/exception.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/filters.rb",
        include_str!("mspec/runner/filters.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/filters/match.rb",
        include_str!("mspec/runner/filters/match.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/filters/profile.rb",
        include_str!("mspec/runner/filters/profile.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/filters/regexp.rb",
        include_str!("mspec/runner/filters/regexp.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/filters/tag.rb",
        include_str!("mspec/runner/filters/tag.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters.rb",
        include_str!("mspec/runner/formatters.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/describe.rb",
        include_str!("mspec/runner/formatters/describe.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/dotted.rb",
        include_str!("mspec/runner/formatters/dotted.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/file.rb",
        include_str!("mspec/runner/formatters/file.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/html.rb",
        include_str!("mspec/runner/formatters/html.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/junit.rb",
        include_str!("mspec/runner/formatters/junit.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/method.rb",
        include_str!("mspec/runner/formatters/method.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/multi.rb",
        include_str!("mspec/runner/formatters/multi.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/profile.rb",
        include_str!("mspec/runner/formatters/profile.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/specdoc.rb",
        include_str!("mspec/runner/formatters/specdoc.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/spinner.rb",
        include_str!("mspec/runner/formatters/spinner.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/summary.rb",
        include_str!("mspec/runner/formatters/summary.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/unit.rb",
        include_str!("mspec/runner/formatters/unit.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/formatters/yaml.rb",
        include_str!("mspec/runner/formatters/yaml.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/mspec.rb",
        include_str!("mspec/runner/mspec.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/object.rb",
        include_str!("mspec/runner/object.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/parallel.rb",
        include_str!("mspec/runner/parallel.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/runner/shared.rb",
        include_str!("mspec/runner/shared.rb"),
    )?;
    interp.def_rb_source_file("mspec/runner/tag.rb", include_str!("mspec/runner/tag.rb"))?;
    interp.def_rb_source_file(
        "mspec/utils/deprecate.rb",
        include_str!("mspec/utils/deprecate.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/utils/name_map.rb",
        include_str!("mspec/utils/name_map.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/utils/options.rb",
        include_str!("mspec/utils/options.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/utils/script.rb",
        include_str!("mspec/utils/script.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/utils/version.rb",
        include_str!("mspec/utils/version.rb"),
    )?;
    interp.def_rb_source_file(
        "mspec/utils/warnings.rb",
        include_str!("mspec/utils/warnings.rb"),
    )?;
    interp.def_rb_source_file("mspec/version.rb", include_str!("mspec/version.rb"))?;
    interp.def_rb_source_file("/src/test/spec_runner.rb", include_str!("spec_runner.rb"))?;
    Ok(())
}
