#![deny(missing_docs, warnings)]
#![deny(clippy::all, clippy::pedantic)]

//! Crate `mruby-sys` is Rust bindings for mruby (currently version 2.0.1),
//! statically linked with FFI API generated by bindgen.

#[allow(missing_docs)]
#[allow(non_camel_case_types)]
#[allow(non_upper_case_globals)]
#[allow(non_snake_case)]
#[allow(clippy::all, clippy::pedantic)]
mod ffi;

pub use self::ffi::*;

#[path = "ffi_tests.rs"]
#[cfg(test)]
mod tests;
