[package]
name = "spinoso-securerandom"
version = "0.2.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
description = """
Secure PRNG backend for Artichoke Ruby, implements 'securerandom' package
"""
keywords = ["artichoke", "rand", "random", "rng", "spinoso"]
categories = ["algorithms"]
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
base64 = { version = "0.20.0", default-features = false, features = ["alloc"] }
rand = { version = "0.8.0", default-features = false, features = ["getrandom"] }
scolapasta-hex = { version = "0.2.0", path = "../scolapasta-hex", default-features = false, features = ["alloc"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
