[package]
name = "spinoso-securerandom"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = """
Secure PRNG backend for Artichoke Ruby, implements 'securerandom' package
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "rand", "random", "rng", "spinoso"]
categories = ["algorithms"]

[dependencies]
base64 = "0.13"
rand = "0.8"

[dependencies.scolapasta-hex]
version = "0.1"
path = "../scolapasta-hex"
default-features = false
features = ["alloc"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
