[package]
name = "spinoso-time"
version = "0.7.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
description = """
Datetime handling for Artichoke Ruby
"""
keywords = ["artichoke", "date", "datetime", "spinoso", "time"]
categories = ["date-and-time"]
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[features]
default = ["tzrs", "tzrs-local"]
tzrs = ["dep:once_cell", "dep:regex", "dep:strftime-ruby", "dep:tz-rs", "dep:tzdb"]
tzrs-local = ["tzrs"]

[dependencies]
once_cell = { version = "1.12.0", optional = true }
regex =  { version = "1.7.0", default-features = false, features = ["std"], optional = true }
strftime-ruby = { version = "1.0.0", default-features = false, features = ["alloc"], optional = true }
tz-rs = { version = "0.6.12", default-features = false, features = ["std"], optional = true }
tzdb = { version = "0.5.0", default-features = false, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
