[package]
name = "spinoso-env"
version = "0.2.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
description = """
Access to environment variables, system or virtualized, for Artichoke Ruby
"""
keywords = ["artichoke", "env", "environ", "spinoso"]
categories = ["os", "wasm"]
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
bstr = { version = "1.4.0", default-features = false }
scolapasta-path = { version = "0.5.0", path = "../scolapasta-path", optional = true }
scolapasta-string-escape = { version = "0.3.0", path = "../scolapasta-string-escape", default-features = false }

[features]
default = ["system-env"]
# Enable an `ENV` implementation that access the system environment via
# `std::env::var_os`. These APIs enable Ruby to manipulate the host system.
system-env = ["dep:scolapasta-path"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
