[package]
name = "spinoso-math"
version = "0.3.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
description = """
Implementation of the Ruby Math module
"""
keywords = ["libm", "math", "no_std", "spinoso"]
categories = ["algorithms", "no-std"]
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
libm = { version = "0.2.6", optional = true }

[features]
default = ["full"]
# Implement the full Ruby `Math` API by including external crates for missing
# `std` APIs.
full = ["dep:libm"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
