[package]
name = "artichoke-backend"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

[dependencies]
backtrace = "0.3"
bstr = "0.2"
log = "0.4"
memchr = "2"
regex = "1"
twoway = "0.2"

[dependencies.artichoke-core]
path = "../artichoke-core"

[dependencies.artichoke-vfs]
path = "../artichoke-vfs"

[dependencies.onig]
version = "5"
# git = "https://github.com/artichoke/rust-onig"
# branch = "wasm"

[dev-dependencies]
env_logger = "0.7"
libc = "0.2"
quickcheck = "0.9"
quickcheck_macros = "0.8"

[build-dependencies]
cc = "1.0"
chrono = "0.4"
fs_extra = "1.1.0"
rayon = "1.2"
rustc_version = "0.2.3"
target-lexicon = "0.8.1"
walkdir = "2"

[build-dependencies.bindgen]
version = "0.51.1"
default-features = false
