[package]
name = "artichoke-backend"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Embeddable VM implementation for Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "mruby", "ruby"]
categories = ["api-bindings"]

[dependencies]
artichoke-core = { version = "0.3", path = "../artichoke-core" }
bstr = { version = "0.2", default-features = false, features = ["std"] }
chrono = "0.4"
dtoa = "0.4"
intaglio = "1.1"
itoa = "0.4"
libm = { version = "0.2", optional = true }
log = "0.4"
once_cell = "1"
rand = { version = "0.7", optional = true }
rand_pcg = { version = "0.2", optional = true }
regex = "1"
spinoso-array = { version = "0.3", path = "../spinoso-array" }
spinoso-exception = { version = "0.1", path = "../spinoso-exception" }
spinoso-securerandom = { version = "0.1", path = "../spinoso-securerandom", optional = true }
spinoso-symbol = { version = "0.1", path = "../spinoso-symbol" }

[dependencies.onig]
git = "https://github.com/artichoke/rust-onig"
rev = "v6.0.0"
default-features = false
optional = true

[dev-dependencies]
libc = "0.2"
quickcheck = { version = "0.9", default-features = false }
quickcheck_macros = "0.9"

[build-dependencies]
bindgen = { version = "0.55.1", default-features = false, features = ["runtime"] }
cc = "1.0"
target-lexicon = "0.11.0"

[features]
default = [
  "core-env-system",
  "core-math-extra",
  "core-random",
  "core-regexp-oniguruma",
  "stdlib-securerandom"
]
core-env-system = []
core-math-extra = ["libm"]
core-random = ["rand", "rand_pcg"]
core-regexp-oniguruma = ["onig"]
native-filesystem-access = []
output-strategy-capture = []
output-strategy-null = ["output-strategy-capture"]
stdlib-securerandom = ["spinoso-securerandom"]
