[package]
name = "artichoke-backend"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
description = "Embeddable VM implementation for Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "ruby"]

[dependencies]
base64 = { version = "0.11", optional = true }
bstr = "0.2"
chrono = "0.4"
dtoa = "0.4"
hex = { version = "0.4", optional = true }
itoa = "0.4"
libm = { version = "0.2", optional = true }
log = "0.4"
once_cell = "1"
os_str_bytes = "1"
rand = { version = "0.7", optional = true }
rand_pcg = { version = "0.2", optional = true }
regex = "1"
smallvec = "1"
uuid = { version = "0.8", optional = true, features = ["v4"] }

[dependencies.artichoke-core]
path = "../artichoke-core"

[dependencies.onig]
git = "https://github.com/artichoke/rust-onig"
rev = "11bc679d45b6799df2866cb4c90e1d542c4ba4c0"

[dev-dependencies]
libc = "0.2"
quickcheck = { version = "0.9", default-features = false }
quickcheck_macros = "0.9"

[build-dependencies]
bindgen = { version = "0.53.1", default-features = false, features = [
  "runtime"
] }
cc = { version = "1.0", features = ["parallel"] }
chrono = "0.4"
num_cpus = "1"
rustc_version = "0.2.3"
target-lexicon = "0.10.0"

[features]
default = [
  "core-env-system",
  "core-math-extra",
  "core-random",
  "stdlib-securerandom"
]
core-env-system = []
core-math-extra = ["libm"]
core-random = ["rand", "rand_pcg"]
stdlib-securerandom = ["base64", "hex", "rand", "uuid"]
