[package]
name = "spinoso-string"
version = "0.20.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
description = """
Encoding-aware string implementation for Ruby String core type in Artichoke Ruby
"""
keywords = ["encoding", "no_std", "spinoso", "string", "utf8"]
categories = ["data-structures", "encoding", "no-std"]
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
bstr = { version = "1.0.0", default-features = false, features = ["alloc"] }
bytecount = "0.6.2"
focaccia = { version = "1.3.1", optional = true, default-features = false }
raw-parts = "1.1.2"
scolapasta-string-escape = { version = "0.3.0", path = "../scolapasta-string-escape", default-features = false }
simdutf8 = { version = "0.1.4", default-features = false }

[dev-dependencies]
quickcheck = { version = "1.0.3", default-features = false }

[features]
default = ["casecmp", "std"]
casecmp = ["focaccia"]
# Enable implementations of traits in `std` like `Error` and `io::Write`.
#
# Enable runtime SIMD dispatch in `bytecount` and `simdutf8` dependencies.
std = ["bytecount/runtime-dispatch-simd", "simdutf8/std"]
# Use an alternate byte buffer backend that ensures string content is always
# followed by a NUL byte. This feature can be used to ensure spinoso strings are
# FFI compatible with C code that expects byte content to be NUL terminated.
always-nul-terminated-c-string-compat = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
