---
name: CI
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"

      # avoid choco because it takes forever to initialize on first use
      # instead, install bison directly from GitHub releases
      - name: Install Bison
        run: |
          $win_flex_bison = ($env:temp) + '\win_flex_bison\'
          (Invoke-WebRequest $env:WIN_FLEX_BISON).Content | Expand-Archive -DestinationPath $win_flex_bison
          echo $win_flex_bison | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        env:
          WIN_FLEX_BISON: https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip
        if: runner.os == 'Windows'

      - name: Check Bison
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows"]; then
            win_bison.exe --version
            win_bison --version
          else
            bison --version
          fi

      - name: Compile
        run: cargo build --workspace --verbose

      - name: Compile tests
        run: cargo test --workspace --no-run

      - name: Test
        run: cargo test --workspace

  build-features:
    name: Build (non-default features)
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"

      - name: Compile with locked Cargo.lock
        run: cargo build --locked

      - name: Compile fuzz with locked Cargo.lock
        run: cargo build --locked
        working-directory: "fuzz"

      - name: Compile spec-runner with locked Cargo.lock
        run: cargo build --locked
        working-directory: "spec-runner"

      - name: Compile artichoke with no default features
        run: cargo build --verbose --no-default-features

      - name: Compile artichoke with all features
        run: cargo build --verbose --all-features

      - name: Compile spinoso-array with no default features
        run: cargo build --verbose --no-default-features
        working-directory: "spinoso-array"

      - name: Compile spinoso-array with all features
        run: cargo build --verbose --all-features
        working-directory: "spinoso-array"

      - name: Compile spinoso-env with no default features
        run: cargo build --verbose --no-default-features
        working-directory: "spinoso-env"

      - name: Compile spinoso-env with all features
        run: cargo build --verbose --all-features
        working-directory: "spinoso-env"

      - name: Compile spinoso-math with no default features
        run: cargo build --verbose --no-default-features
        working-directory: "spinoso-math"

      - name: Compile spinoso-math with all features
        run: cargo build --verbose --all-features
        working-directory: "spinoso-math"

      - name: Compile spinoso-random with no default features
        run: cargo build --verbose --no-default-features
        working-directory: "spinoso-random"

      - name: Compile spinoso-random with all features
        run: cargo build --verbose --all-features
        working-directory: "spinoso-random"

      - name: Compile spinoso-random with some features
        run: |
          cargo build --verbose --no-default-features --features rand_core
          cargo build --verbose --no-default-features --features std
          cargo build --verbose --no-default-features --features rand
        working-directory: "spinoso-random"

      - name: Compile spinoso-symbol with no default features
        run: cargo build --verbose --no-default-features
        working-directory: "spinoso-symbol"

      - name: Compile spinoso-symbol with all features
        run: cargo build --verbose --all-features
        working-directory: "spinoso-symbol"

      - name: Compile spinoso-symbol with some features
        run: |
          cargo build --verbose --no-default-features --features ident-parser
          cargo build --verbose --no-default-features --features inspect
          cargo build --verbose --no-default-features --features inspect,artichoke
        working-directory: "spinoso-symbol"

      - name: Compile scolapasta-hex with no default features
        run: cargo build --verbose --no-default-features
        working-directory: "scolapasta-hex"

      - name: Compile scolapasta-hex with all features
        run: cargo build --verbose --all-features
        working-directory: "scolapasta-hex"

      - name: Compile scolapasta-hex with some features
        run: |
          cargo build --verbose --no-default-features --features alloc
          cargo build --verbose --no-default-features --features alloc,std
        working-directory: "scolapasta-hex"

      - name: Compile scolapasta-string-escape with no default features
        run: cargo build --verbose --no-default-features
        working-directory: "scolapasta-string-escape"

      - name: Compile scolapasta-string-escape with all features
        run: cargo build --verbose --all-features
        working-directory: "scolapasta-string-escape"

  rust:
    name: Lint and format Rust
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"

      - name: Check formatting
        run: cargo fmt -- --check --color=auto

      - name: Lint with Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --all-features

  ruby:
    name: Lint and format Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Lint and check formatting with Rubocop
        run: bundle exec rubocop --format github

  c:
    name: Lint and format C
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint and check formatting with clang-format
        run: npx github:artichoke/clang-format --check

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint and check formatting with prettier
        run: npx prettier --check '**/*'

      - name: Lint YAML sources with yamllint
        run: |
          sudo -H python3 -m pip install --upgrade pip setuptools wheel
          sudo -H python3 -m pip install --upgrade yamllint
          yamllint --version
          echo "Linting YAML sources with yamllint ..."
          yamllint --strict .
          echo "OK"
