---
name: Crash
"on":
  pull_request:
    branches:
      - trunk
env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
jobs:
  crash:
    name: Crash
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1.12.1
        with:
          toolchain: "1.83.0"

      - name: Compile debug
        run: cargo build --verbose --bin spec-runner
        working-directory: "spec-runner"

      - name: Compile release
        run: cargo build --verbose --bin spec-runner --release
        working-directory: "spec-runner"

      - name: Run specs
        run: |
          ./target/debug/spec-runner --quiet --format artichoke all-core-specs.toml > /dev/null
          ./target/debug/spec-runner --quiet --format summary all-core-specs.toml > /dev/null
          ./target/debug/spec-runner --quiet --format tagger all-core-specs.toml > /dev/null
          ./target/debug/spec-runner --quiet --format yaml all-core-specs.toml > /dev/null
        working-directory: "spec-runner"
        env:
          PERNOSCO_ENABLE: 1

      - name: Run specs
        run: |
          ./target/debug/spec-runner --quiet --format artichoke spec-state.toml > /dev/null
          ./target/debug/spec-runner --quiet --format summary spec-state.toml > /dev/null
          ./target/debug/spec-runner --quiet --format tagger spec-state.toml > /dev/null
          ./target/debug/spec-runner --quiet --format yaml spec-state.toml > /dev/null
        working-directory: "spec-runner"
        env:
          PERNOSCO_ENABLE: 1

      - name: Run specs
        run: |
          ./target/release/spec-runner --quiet --format artichoke all-core-specs.toml > /dev/null
          ./target/release/spec-runner --quiet --format summary all-core-specs.toml > /dev/null
          ./target/release/spec-runner --quiet --format tagger all-core-specs.toml > /dev/null
          ./target/release/spec-runner --quiet --format yaml all-core-specs.toml > /dev/null
        working-directory: "spec-runner"
        env:
          PERNOSCO_ENABLE: 1

      - name: Run specs
        run: |
          ./target/release/spec-runner --quiet --format artichoke spec-state.toml > /dev/null
          ./target/release/spec-runner --quiet --format summary spec-state.toml > /dev/null
          ./target/release/spec-runner --quiet --format tagger spec-state.toml > /dev/null
          ./target/release/spec-runner --quiet --format yaml spec-state.toml > /dev/null
        working-directory: "spec-runner"
        env:
          PERNOSCO_ENABLE: 1
