---
name: Crash
"on":
  pull_request:
    branches:
      - trunk
jobs:
  crash:
    name: Crash
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        run: |
          echo "::group::rustup toolchain install"
          rustup toolchain install nightly --profile minimal
          echo "::endgroup::"
          echo "::group::set default toolchain"
          rm -rf rust-toolchain
          rustup default nightly
          echo "::endgroup::"
          echo "::group::rustup version"
          rustup -Vv
          echo "::endgroup::"
          echo "::group::rustc version"
          rustc -Vv
          echo "::endgroup::"
          echo "::group::cargo version"
          cargo version --verbose
          echo "::endgroup::"

      - name: Compile debug
        run: cargo build --verbose --bin spec-runner
        working-directory: "spec-runner"

      - name: Compile release
        run: cargo build --verbose --bin spec-runner --release
        working-directory: "spec-runner"

      - name: Run specs
        run: |
          ./target/debug/spec-runner --quiet --format artichoke all-core-specs.toml > /dev/null
          ./target/debug/spec-runner --quiet --format summary all-core-specs.toml > /dev/null
          ./target/debug/spec-runner --quiet --format tagger all-core-specs.toml > /dev/null
          ./target/debug/spec-runner --quiet --format yaml all-core-specs.toml > /dev/null
        working-directory: "spec-runner"
        env:
          PERNOSCO_ENABLE: 1

      - name: Run specs
        run: |
          ./target/debug/spec-runner --quiet --format artichoke spec-state.toml > /dev/null
          ./target/debug/spec-runner --quiet --format summary spec-state.toml > /dev/null
          ./target/debug/spec-runner --quiet --format tagger spec-state.toml > /dev/null
          ./target/debug/spec-runner --quiet --format yaml spec-state.toml > /dev/null
        working-directory: "spec-runner"
        env:
          PERNOSCO_ENABLE: 1

      - name: Run specs
        run: |
          ./target/release/spec-runner --quiet --format artichoke all-core-specs.toml > /dev/null
          ./target/release/spec-runner --quiet --format summary all-core-specs.toml > /dev/null
          ./target/release/spec-runner --quiet --format tagger all-core-specs.toml > /dev/null
          ./target/release/spec-runner --quiet --format yaml all-core-specs.toml > /dev/null
        working-directory: "spec-runner"
        env:
          PERNOSCO_ENABLE: 1

      - name: Run specs
        run: |
          ./target/release/spec-runner --quiet --format artichoke spec-state.toml > /dev/null
          ./target/release/spec-runner --quiet --format summary spec-state.toml > /dev/null
          ./target/release/spec-runner --quiet --format tagger spec-state.toml > /dev/null
          ./target/release/spec-runner --quiet --format yaml spec-state.toml > /dev/null
        working-directory: "spec-runner"
        env:
          PERNOSCO_ENABLE: 1
